In [12]:
import numpy
x = numpy.random.randint(0,10,(3,3,3))
y = numpy.random.randint(0,10,(3,3,3))
x,y,x+y,x.shape,x.ndim,x.dtype,x.size

(array([[[8, 8, 7],
         [4, 8, 6],
         [9, 8, 9]],
 
        [[1, 0, 6],
         [1, 0, 9],
         [5, 2, 6]],
 
        [[4, 0, 9],
         [9, 2, 4],
         [0, 3, 8]]], dtype=int32),
 array([[[7, 8, 0],
         [1, 1, 3],
         [7, 4, 5]],
 
        [[4, 3, 1],
         [8, 7, 2],
         [0, 4, 6]],
 
        [[8, 6, 5],
         [4, 9, 2],
         [8, 0, 7]]], dtype=int32),
 array([[[15, 16,  7],
         [ 5,  9,  9],
         [16, 12, 14]],
 
        [[ 5,  3,  7],
         [ 9,  7, 11],
         [ 5,  6, 12]],
 
        [[12,  6, 14],
         [13, 11,  6],
         [ 8,  3, 15]]], dtype=int32),
 (3, 3, 3),
 3,
 dtype('int32'),
 27)